variables:
  CODECOV_TOKEN: "CODECOV_TOKEN_STRING"

before_script:
  - apt-get update -qq
  - apt-get install -y --no-install-recommends libcurl4-openssl-dev libssh2-1-dev libssl-dev git libxml2-dev
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=TRUE

r-base:
  stage: test
  image: r-base:latest
  script:
    - Rscript -e 'install.packages(c("devtools", "roxygen2", "covr"))'
    - Rscript -e 'devtools::install_github("hadley/devtools")'
    - Rscript -e 'devtools::install_dev_deps()'
    - Rscript -e 'devtools::check()'
    - Rscript -e 'covr::codecov(type = "all", quiet = FALSE)'
  tags:
    - docker
