# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.5
  - 3.4
  - 3.3

r_github_packages:
  - dviraran/xCell
  - GfellerLab/EPIC
  - ebecht/MCPcounter/Source
  - bmbolstad/preprocessCore

install:
  # Install dependencies for default R packages
  - R -e "install.packages('devtools')"
  # - R -e "install.packages('pkgdown')"
  - R -e "devtools::install_deps(dep=TRUE)"

script:
  # Test regular R package
  - which R
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e "pkgdown::build_site()"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

sudo: false
cache: packages
