# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-devel
  - bioc-release
r_github_packages:
  - dviraran/xCell
  - GfellerLab/EPIC
  - ebecht/MCPcounter/Source
  - bmbolstad/preprocessCore
sudo: false
cache: packages
